[package]
name = "rrplug"
version = "0.2.0"
authors = ["catornot"]
description = "safe wrappers and functions for R2Northstar plugins"
repository = "https://github.com/catornot/rrplug"
license = "MIT"
keywords = ["plugin", "northstar", "titanfall"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.37"
log = "0.4.17"
once_cell = "1.16.0"
rrplug_proc = {path = "./rrplug_proc" }

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-pc-windows-msvc"]