[package]
name = "r2plugins-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r2rsplugins = { path = "./r2rsplugins" }

[build-dependencies]
windres = "0.2.2"

[lib]
crate-type = ["cdylib"]