[placeholders.description]
type = "string"
prompt = "Description of the project:"
default = ""

[placeholders.run_on_server]
type = "bool"
prompt = "Is this a server plugin?"
default = false

[placeholders.run_on_client]
type = "bool"
prompt = "Is this a client plugin?"
default = true

[placeholders.example]
type = "bool"
prompt = "Do you want example code?"
default = false