name: rrplug-test-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3.2.2
      with:
        path: /target
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
